Laboratorio3/Models/PersonaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class PersonaModel
    {
		public string Nombre { get; set; }
		public int Id { get; set; }
		public double Peso { get; set; }
		public double Estatura { get; set; }

		public PersonaModel()
		{
			this.Nombre = "Sin nombre";
			this.Id = 0;
			this.Peso = 0.0;
			this.Estatura = 0.0;
		}

		public PersonaModel(int Id, string Nombre, double Peso, double Estatura)
		{
			this.Nombre = Nombre;
			this.Id = Id;
			this.Peso = Peso;
			this.Estatura = Estatura;
		}
	}
}

Laboratorio3/Controllers/CalculadoraIMCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio3.Models;

namespace Laboratorio3.Controllers
{
    public class CalculadoraIMCController : Controller
    {

		public ActionResult ResultadoIMC()
		{
			PersonaModel persona = new PersonaModel(1, "Cristiano Ronaldo", 84.0, 1.87);
			double IMC = persona.Peso / (persona.Estatura * persona.Estatura);
			ViewBag.IMC = IMC;
			ViewBag.persona = persona;
			return View();
		}

		public ActionResult ResultadosAleatoriosIMC()
        {
			List <PersonaModel> personas = new List<PersonaModel>();
			Random random = new Random();

			for (int i = 0; i < 30; i++)
            {
				personas.Add(new PersonaModel {Id = i + 1, Nombre = "Sin nombre", Peso = random.NextDouble() * (150.0 - 20.0) + 20.0, Estatura = random.NextDouble() * (2.0 - 1.0) + 1.0 });			
				ViewBag.persona = personas;
			}


			return View();
        }
	}
}

Laboratorio3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Laboratorio3/Views/CalculadoraIMC/ResultadoIMC.cshtml
@{ 
    ViewBag.Title = "IMC";
}
<!DOCTYPE html>
<html>
    <head>
        <title> Resultado IMC </title>
        <meta charset="uft-8" />
    </head>
    <body>
        <h1>Resultado</h1>
        <div class="seccion_1" id="s1">

            <table class="table-bordered">
                <tr>
                    <th>Encabezado 1</th>
                    <th>Encabezado 2</th>
                    <th>Encabezado 3</th>
                </tr>

                <tr>
                    <td>@ViewBag.Persona.Nombre</td>
                    <td>Fila 1, Columna 2</td>
                    <td>Fila 1, Columna 3</td>
                </tr>

                <tr>
                    <td>Fila 2, Columna 1</td>
                    <td>Fila 2, Columna 2</td>
                    <td>Fila 2, Columna 3</td>
                </tr>
            </table>
            <hr />
        </div>

        <div class="seccion_2" id="s2">
            <ul>
                <li> Elemento 1 </li>
                <li> Elemento 2 </li>
                <li> Elemento 3 </li>
            </ul>
            <hr />
        </div>

        <div class="seccion_3" id="s3">
            <input type="button" value="Soy un Boton" /> <hr />
            <a href="/Home/" class="btn btn-info"> Soy un link que parece boton </a>
        </div>

        <div class="seccion_4">
            @if(ViewBag.IMC > 20)
            {
                <div class="text-succes">
                    <p>Mensaje</p>
                </div>
            }
            else
            {
                <div class="text-danger">
                    <p>Otro mensaje</p>
                </div>
            }
        </div>
    </body>
</html>

Laboratorio3/Views/CalculadoraIMC/ResultadosAleatoriosIMC.cshtml
@{ 
    ViewBag.Title = "IMC";
}
<!DOCTYPE html>
<html>
    <head>
        <title> Resultado IMC </title>
        <meta charset="uft-8" />
    </head>
    <body>
        <h1>Resultados</h1>
        <div class="seccion_1" id="s1">
            <ul>
                <li> IMC menor que 18,5 -> peso insuficiente </li>
                <li> IMC entre 18,5 y 24,9 -> peso normal </li>
                <li> IMC mayor que 25 -> sobrepeso </li>
            </ul>
            <a href="/Home/" class="btn btn-info"> Volver al inicio </a>
            <hr />
        </div>

        <div class="seccion_2" id="s2">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Peso</th>
                    <th>Estatura</th>
                    <th>IMC</th>
                </tr>

                @foreach (var persona in ViewBag.persona)
                {
            <tr>
                <td>@persona.Id</td>
                <td>@persona.Nombre</td>
                <td>@persona.Peso</td>
                <td>@persona.Estatura</td>
                @{
                    double IMC = persona.Peso / (persona.Estatura * persona.Estatura);
                    if (IMC <= 24.9 && IMC >= 18.5)
                    {
                        <td style="color: green">@IMC</td>
                    }
                    else
                    {
                        <td style="color: red">@IMC</td>
                    }
                }
            </tr>
                }

            </table>
        </div>

    </body>
</html>

Laboratorio3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Laboratorio3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Laboratorio3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Laboratorio3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("IMC", "ResultadoIMC", "CalculadoraIMC")</li>
                    <li>@Html.ActionLink("IMC aleatorio", "ResultadosAleatoriosIMC", "CalculadoraIMC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>